<?php
$DBVARS=array(
 'username'=>'root',
 'password'=>'',
 'hostname'=>'localhost',
 'db_name'=>'ycms',
 'theme'=>'basic',
 'plugins'=>'page-comments,forms,image-gallery,panels,content-snippet',
 'page-comments|version'=>'2',
 'page-comments|moderation_email'=>'marcinbrodowski@gmail.com',
 'page-comments|moderation_enabled'=>'yes',
 'forms|version'=>'3',
 'panels|version'=>'4',
 'content-snippet|version'=>'1'
);